import type { MediaItem, Memory } from './types';

/**
 * ============================================================
 *  TIMELINE — October 6, 2025 → October 6, 2026
 * ============================================================
 * Every memory below comes from Winston's own account. Nothing is invented.
 *
 *  • `chapter` places a memory inside a chapter defined in story.ts.
 *  • `drafted: true` = the narration was written from Winston's notes.
 *    Review the wording; it's yours to change.
 *  • `quote` is ONLY for real words from a real message/recording.
 *  • Media: drop the file at the `src` path and it appears automatically.
 *    Until then a labelled placeholder shows instead. `status` says whether
 *    Winston already has it ('have') or still needs to find it ('find').
 *    Full list: ASSET_CHECKLIST.md
 */

type Kind = MediaItem['type'];
const media = (
  type: Kind,
  src: string,
  label: string,
  alt: string,
  status: 'have' | 'find',
  orientation: MediaItem['orientation'] = 'portrait',
  extra: Partial<MediaItem> = {},
): MediaItem => ({ type, src, label, alt, status, orientation, ...extra });

export const timeline: Memory[] = [
  /* ───────────── I · THE STORM — late October 2025 ───────────── */
  {
    id: 'hurricane',
    chapter: 'storm',
    date: '2025-10-25',
    dateLabel: 'Late October 2025',
    dateCertainty: 'approximate',
    title: 'Hurricane Melissa',
    shortText: 'You kept telling me to take it seriously.',
    longText: [
      'Honestly, I didn’t. Not until the day before.',
      'I checked on my granddad, then went to my dad’s house to ride it out.',
    ],
    tone: 'difficult',
    significance: 'medium',
    treatment: 'quiet',
    mood: 'storm',
    drafted: true,
  },
  {
    id: 'night-before',
    chapter: 'storm',
    date: '2025-10-26',
    dateLabel: 'The night before',
    dateCertainty: 'approximate',
    title: 'The night before, you helped me forgive myself.',
    shortText: 'It was our last conversation before the silence.',
    tone: 'tender',
    significance: 'small',
    treatment: 'quiet',
    mood: 'storm',
    drafted: true,
  },
  {
    id: 'silence-and-signal',
    chapter: 'storm',
    date: '2025-10-28',
    dateLabel: 'Two or three days later',
    dateCertainty: 'approximate',
    kicker: 'After the storm',
    title: 'No power. No water. No way to reach you.',
    shortText: 'Then a community Starlink came online.',
    longText: [
      'I ran about two miles to get a signal, just to tell you I was okay.',
      'You were so relieved. So happy.',
    ],
    tone: 'difficult',
    significance: 'major',
    treatment: 'relationship',
    transitionIn: 'dark',
    relationship: {
      there: 'You',
      here: 'Me',
      severed: { lostLabel: 'No signal', foundLabel: 'Connected' },
    },
    media: [
      media('image', '/assets/hurricane/aftermath-1.jpg', 'Aftermath photo', 'The aftermath of Hurricane Melissa', 'find', 'landscape'),
      media('screenshot', '/assets/hurricane/im-okay-message.jpg', '“I’m okay” message', 'The first message after the hurricane', 'find'),
    ],
    drafted: true,
  },
  {
    id: 'late-night-wifi',
    chapter: 'storm',
    date: '2025-11-05',
    dateLabel: 'The weeks after',
    dateCertainty: 'period',
    title: 'Late nights at the community Wi‑Fi',
    shortText: 'A few minutes with you at a time. I missed you every day.',
    tone: 'tender',
    significance: 'small',
    treatment: 'quiet',
    mood: 'tender',
    drafted: true,
  },
  {
    id: 'meeting-uncle',
    chapter: 'storm',
    date: '2025-11-08',
    dateLabel: 'Around then',
    dateCertainty: 'period',
    title: 'And somehow, you met my uncle.',
    shortText: '[THE UNCLE STORY — Winston will add the details]',
    tone: 'funny',
    significance: 'small',
    treatment: 'quiet',
    mood: 'warm',
  },

  /* ───────────── II · OUR FIRST CHRISTMAS — December 2025 ───────────── */
  {
    id: 'first-christmas',
    chapter: 'christmas',
    date: '2025-12-25',
    dateLabel: 'December 2025',
    dateCertainty: 'period',
    title: 'Our first Christmas',
    shortText: 'You were with family. Time to talk was short, and not every moment was easy. But it was our first Christmas together.',
    tone: 'tender',
    significance: 'small',
    treatment: 'quiet',
    mood: 'warm',
    drafted: true,
  },
  {
    id: 'christmas-feast',
    chapter: 'christmas',
    date: '2025-12-26',
    dateLabel: 'Christmas 2025',
    dateCertainty: 'period',
    title: 'Untouched by the hurricane',
    shortText: 'You joked that the hurricane clearly hadn’t touched me at all…',
    tone: 'funny',
    significance: 'small',
    treatment: 'discover',
    mood: 'joy',
    reveal: {
      prompt: 'Look at my plate',
      items: ['Mutton', 'Fried chicken', 'Curry', 'Pork'],
      after: '…and so forth.',
    },
    drafted: true,
  },

  /* ───────────── III · THE COMEBACK — December 2025 → April 2026 ───────────── */
  {
    id: 'comeback-plan',
    chapter: 'comeback',
    date: '2025-12-28',
    dateLabel: 'Before the January semester',
    dateCertainty: 'period',
    title: 'The plan',
    tone: 'proud',
    significance: 'medium',
    treatment: 'steps',
    mood: 'journey',
    steps: [
      { when: 'Fall 2025', label: 'A hard semester', text: 'Your GPA fell further than you wanted it to.' },
      { when: 'Before January', label: 'What you needed', text: 'You said you needed a 3.8.' },
      { label: 'What I saw', text: '4.0 sort of student', quote: true },
      { label: 'The goal', text: 'So we aimed for straight A’s.' },
    ],
    drafted: true,
  },
  {
    id: 'one-year-with-christ',
    chapter: 'comeback',
    date: '2026-01-15',
    dateLabel: 'January 2026',
    dateCertainty: 'period',
    title: 'One year walking with Christ',
    shortText: 'January marked a year since you began walking with Christ.',
    tone: 'faith',
    significance: 'medium',
    treatment: 'quiet',
    mood: 'grace',
    faith: {
      reflection:
        'This was the year faith stopped being something you talked about and became something you lived: in your choices, your challenges, your character.',
    },
    drafted: true,
  },
  {
    id: 'valentines',
    chapter: 'comeback',
    date: '2026-02-14',
    dateCertainty: 'exact',
    title: 'Valentine’s',
    shortText: 'I built you a website: an old-English letter, games, Bible trivia. Flowers and Kisses too. You gave me a book.',
    tone: 'tender',
    significance: 'small',
    treatment: 'video',
    mood: 'tender',
    media: [media('video', '/assets/valentines/valentines-site.mp4', 'Valentine’s website screen recording', 'A screen recording of the Valentine’s website', 'have', 'portrait', { poster: '/assets/valentines/valentines-site-poster.jpg' })],
    drafted: true,
  },
  {
    id: 'learning-makeup',
    chapter: 'comeback',
    date: '2026-03-28',
    dateLabel: 'The weeks before the gala',
    dateCertainty: 'period',
    title: 'Learning makeup',
    shortText: 'You got makeup and started teaching yourself, weeks ahead of the gala. Trying, practising, getting better.',
    tone: 'joyful',
    significance: 'medium',
    treatment: 'joyful',
    mood: 'joy',
    media: [
      media('image', '/assets/gala/practice-1.jpg', 'Makeup practice: early attempt', 'Gia experimenting with makeup', 'have', 'portrait'),
      media('image', '/assets/gala/practice-2.jpg', 'Makeup practice', 'Gia practising her makeup', 'have', 'portrait'),
      media('image', '/assets/gala/practice-3.jpg', 'Makeup practice: growing confidence', 'Gia growing more confident with makeup', 'have', 'square'),
    ],
    drafted: true,
  },
  {
    id: 'gala',
    chapter: 'comeback',
    date: '2026-04-25', // from Winston's recollection; editable
    dateCertainty: 'approximate',
    dateLabel: 'April 25, 2026',
    kicker: 'All that practice',
    title: 'The gala',
    shortText: 'You looked amazing.',
    longText: ['The finished look was all yours: the creativity, the confidence, the weeks of effort behind it.'],
    tone: 'joyful',
    significance: 'turning',
    treatment: 'cinematic',
    transitionIn: 'light',
    mood: 'warm',
    media: [media('image', '/assets/gala/gala-1.jpg', 'Gala photo (the finished look)', 'Gia at the gala', 'have', 'portrait')],
    drafted: true,
  },
  {
    id: 'rising-star',
    chapter: 'comeback',
    date: '2026-04-30',
    dateCertainty: 'exact',
    kicker: 'You did the work',
    title: 'The Rising Star Award',
    shortText: 'Barry University, April 30, 2026.',
    longText: ['From January to April, you put in the work.', 'The award has your name on it because the work did.'],
    tone: 'proud',
    significance: 'major',
    treatment: 'cinematic',
    mood: 'warm',
    media: [media('image', '/assets/comeback/rising-star-award.jpg', 'Gia with the Rising Star Award', 'Gia holding Barry University’s Rising Star Award', 'have', 'portrait')],
    drafted: true,
  },

  /* ───────────── IV · MAY — trust, and two milestones ───────────── */
  {
    id: 'home-for-summer',
    chapter: 'may',
    date: '2026-05-05',
    dateLabel: 'Early May 2026',
    dateCertainty: 'approximate',
    title: 'Home to California',
    shortText: 'You went home to California with your brother after the semester. We thought there’d be more time to talk. Being around family made it harder.',
    tone: 'neutral',
    significance: 'small',
    treatment: 'quiet',
    mood: 'journey',
    drafted: true,
  },
  {
    id: 'choosing-trust',
    chapter: 'may',
    date: '2026-05-10',
    dateCertainty: 'exact',
    title: 'Choosing trust',
    shortText: 'Instagram showed me as active when I wasn’t. You felt forgotten, and I understood why it hurt.',
    longText: [
      'Part of you wanted to pull away. You chose not to.',
      'We talked it through. Then we introduced ourselves to each other all over again, and laughed.',
      'I was proud of you.',
    ],
    tone: 'tender',
    significance: 'medium',
    treatment: 'quiet',
    mood: 'tender',
    drafted: true,
  },
  {
    id: 'may-12',
    chapter: 'may',
    date: '2026-05-12',
    dateCertainty: 'exact',
    kicker: 'Two milestones',
    title: 'One day',
    shortText: 'May 12, 2026',
    longText: ['Your 4.0, confirmed. Our first anniversary. On the same day.', 'Two milestones in one day. It felt amazing.'],
    tone: 'joyful',
    significance: 'turning',
    treatment: 'figures',
    mood: 'joy',
    figures: [
      { value: '4.0', label: 'Straight A’s' },
      { value: '1', label: 'Year together' },
    ],
    media: [
      media('screenshot', '/assets/anniversary/four-point-oh-message.jpg', '“I got a 4.0” message', 'Gia’s message announcing her 4.0', 'find'),
      media('screenshot', '/assets/anniversary/anniversary-screenshot.jpg', 'Anniversary screenshot', 'A screenshot from our first anniversary', 'find'),
    ],
    drafted: true,
  },
  {
    id: 'gifts-to-jamaica',
    chapter: 'may',
    date: '2026-05-12',
    dateLabel: 'Also May 12',
    dateCertainty: 'approximate',
    title: 'The anniversary gifts went to my address in Jamaica.',
    shortText: 'Instead of yours. They’re still here at my house.',
    tone: 'funny',
    significance: 'small',
    treatment: 'floating',
    mood: 'joy',
    media: [media('image', '/assets/anniversary/gifts-in-jamaica.jpg', 'The anniversary gifts', 'The anniversary gifts, still at Winston’s house', 'find', 'square')],
    drafted: true,
  },
  {
    id: 'intentionality-seed',
    chapter: 'may',
    date: '2026-05-20',
    dateLabel: 'May 2026',
    dateCertainty: 'period',
    title: 'Something you wanted back',
    shortText:
      'You told me a past relationship had taught you to hold back the spontaneous, romantic things, because they weren’t appreciated. You said you wanted to bring that back.',
    tone: 'tender',
    significance: 'small',
    treatment: 'quiet',
    mood: 'tender',
    drafted: true,
  },

  /* ───────────── V · SUMMER — best friends ───────────── */
  {
    id: 'best-friends',
    chapter: 'summer',
    date: '2026-06-01',
    dateLabel: 'Early June 2026',
    dateCertainty: 'approximate',
    title: 'Best friends',
    shortText: 'Around the start of June, we started calling each other best friends.',
    tone: 'joyful',
    significance: 'small',
    treatment: 'quiet',
    mood: 'joy',
    drafted: true,
  },
  {
    id: 'summer-of-trying',
    chapter: 'summer',
    date: '2026-06-15',
    dateLabel: 'Summer 2026',
    dateCertainty: 'period',
    title: 'The summer you tried everything',
    shortText: 'Fitness. Skipping rope. Handstands. Tricks. Sign language.',
    longText: [
      'We spent a whole day trying things together on calls.',
      'And somehow the running joke became that I was good at sign language. I was not.',
    ],
    tone: 'joyful',
    significance: 'major',
    treatment: 'joyful',
    mood: 'joy',
    media: [
      media('video', '/assets/summer/tricks.mp4', 'Tricks / handstands recording', 'Trying tricks and handstands on a call', 'have', 'portrait', { ambient: true }),
      media('video', '/assets/summer/sign-language.mp4', 'Sign-language recording', 'Trying sign language on a call', 'have', 'portrait', { ambient: true }),
      media('screenshot', '/assets/summer/call-screenshot.jpg', 'Summer call screenshot', 'A screenshot from a summer call', 'have', 'portrait'),
    ],
    drafted: true,
  },
  {
    id: 'ring-size',
    chapter: 'summer',
    date: '2026-06-19',
    dateCertainty: 'exact',
    title: 'After asking for ages',
    shortText: 'Out shopping with your mom, you finally told me your ring size.',
    tone: 'funny',
    significance: 'small',
    treatment: 'discover',
    mood: 'tender',
    reveal: { prompt: 'Open it', items: ['8.5'] },
    drafted: true,
  },

  {
    id: 'nail-milestone',
    chapter: 'summer',
    date: '2026-07-15',
    dateLabel: 'Summer 2026', // exact timing unconfirmed; before the deliverance
    dateCertainty: 'period',
    title: '[THE NAIL-BITING MILESTONE: Winston to add the details]',
    shortText: '[One line, in your words]',
    tone: 'proud',
    significance: 'small',
    treatment: 'quiet',
    mood: 'joy',
  },
  /* ───────────── VI · ANSWERED PRAYER — faith & mentorship ───────────── */
  {
    id: 'baptism-anniversary',
    chapter: 'faith',
    date: '2026-06-08',
    dateCertainty: 'exact',
    title: 'One year since your baptism',
    shortText: 'June 8.',
    tone: 'faith',
    significance: 'medium',
    treatment: 'faith',
    mood: 'grace',
    media: [media('image', '/assets/faith/baptism.jpg', 'Baptism photo or video still', 'Gia’s baptism', 'find', 'portrait')],
    faith: {
      reflection: 'I watched you grow this year: in how you carried hard things, how you kept seeking God, and how you lived what you believe.',
    },
    drafted: true,
  },
  {
    id: 'mentorship',
    chapter: 'faith',
    date: '2026-06-10',
    dateCertainty: 'approximate',
    kicker: 'An answered prayer',
    title: 'A prayer that became people',
    tone: 'faith',
    significance: 'major',
    treatment: 'steps',
    mood: 'grace',
    steps: [
      { label: 'You saw it first', text: 'You wanted mentors before I understood why.' },
      { when: 'June 10, 2026', label: 'Your prayer', text: 'You asked God for guidance: someone to help you see whether you were being wise, and to help with people-pleasing.' },
      { label: 'Leave it to God', text: 'We didn’t know who it would be.' },
      { when: 'That summer', label: 'An invitation', text: 'Brother Linton invited me to his wedding. I mentioned I was courting. Afterwards, he brought it up again.' },
      { label: 'A hug, and a prayer', text: 'On a day I was running on empty, Mrs. Linton hugged me and prayed over me. That’s when I understood.' },
      { when: 'Now', label: 'Every Friday', text: 'They teach us, guide us, and share their wisdom.' },
    ],
    reflection: { label: 'Answered prayer', text: 'You prayed for guidance. God answered with people.', mood: 'grace' },
    media: [media('image', '/assets/mentorship/friday-meeting.jpg', 'Mentorship (optional, no stock images)', 'A Friday mentorship call', 'find', 'landscape')],
    drafted: true,
  },
  {
    id: 'purpose',
    chapter: 'faith',
    date: '2026-06-11',
    dateCertainty: 'exact',
    title: 'Why you do it',
    shortText: 'You told me your motivation was changing: less about titles and admiration, more about helping, nurturing, loving, and fulfilling God’s purpose.',
    tone: 'faith',
    significance: 'small',
    treatment: 'quiet',
    mood: 'grace',
    drafted: true,
  },
  {
    id: 'courage',
    chapter: 'faith',
    date: '2026-07-09',
    dateLabel: 'Around July 9–10, 2026',
    dateCertainty: 'approximate',
    title: 'Courage in the back seat',
    shortText: 'Finding a church home this summer was hard.',
    longText: [
      'You also felt more convicted about reaching people, so you started talking with your Uber drivers.',
      'You were proud of yourself for putting yourself out there. I was proud of you for trying.',
    ],
    tone: 'faith',
    significance: 'medium',
    treatment: 'quiet',
    mood: 'grace',
    drafted: true,
  },

  {
    id: 'deliverance',
    chapter: 'faith',
    date: '2026-07-25',
    dateLabel: 'Summer 2026', // exact date unknown; distinct from the Sept–Oct fast
    dateCertainty: 'period',
    kicker: 'Our testimony',
    title: 'Deliverance',
    // Winston's own account goes here: personal testimony and spiritual understanding only
    shortText: '[YOUR TESTIMONY OF THE DELIVERANCE: Winston to write this in his own words]',
    tone: 'faith',
    significance: 'medium',
    treatment: 'quiet',
    mood: 'grace',
  },
  /* ───────────── VII · STEPS TOWARD YOUR CALLING — dentistry & driving ───────────── */
  {
    id: 'shadowing',
    chapter: 'calling',
    date: '2026-06-25',
    dateLabel: 'Summer 2026',
    dateCertainty: 'period',
    title: 'Dental shadowing',
    shortText: 'You started shadowing, and kept working toward more hours.',
    longText: ['You got busier, and I missed you more.', 'But you were taking real steps toward the work you feel called to: helping people.'],
    tone: 'proud',
    significance: 'medium',
    treatment: 'floating',
    mood: 'warm',
    media: [media('image', '/assets/dentistry/shadowing.jpg', 'Dental-shadowing photo', 'Gia during dental shadowing', 'find', 'portrait')],
    drafted: true,
  },
  {
    id: 'licence',
    chapter: 'calling',
    date: '2026-07-07',
    dateCertainty: 'approximate',
    kicker: 'Nineteen, and never driven',
    title: 'Behind the wheel',
    tone: 'proud',
    significance: 'major',
    treatment: 'steps',
    mood: 'journey',
    steps: [
      { label: 'The first time', text: 'Your first time ever behind the wheel.' },
      { label: 'About a month', text: 'Roughly a month to learn, with only a few lessons.' },
      { when: 'July 7, 2026', label: 'The written test', text: 'Passed.' },
      { when: 'August 19, 2026', label: 'The DMV', text: 'You asked me to pray.' },
      { when: 'August 20, 2026', label: 'Licensed', text: 'You were telling me you had your licence.' },
    ],
    drafted: true,
  },
  {
    id: 'licence-moment',
    chapter: 'calling',
    date: '2026-08-20',
    dateLabel: 'August 2026',
    dateCertainty: 'approximate',
    title: 'Licensed',
    shortText: 'For us, it was faith, courage, and God’s provision.',
    tone: 'proud',
    significance: 'small',
    treatment: 'video',
    mood: 'warm',
    media: [media('video', '/assets/driving/licence.mp4', 'Licence recording', 'A recording from getting the licence', 'have', 'portrait', { poster: '/assets/driving/licence-poster.jpg' })],
    drafted: true,
  },

  /* ───────────── VIII · LOVE, SHOWN — the thread from May resolves ───────────── */
  {
    id: 'intentional-gifts',
    chapter: 'love',
    date: '2026-09-25',
    dateLabel: 'Recently',
    dateCertainty: 'period',
    kicker: 'Remember what you said in May?',
    title: 'You brought it back',
    shortText: 'Thoughtful gifts, a pull-up bar among them. Exactly the kinds of things I’d want.',
    longText: ['You were intentional about it, and excited to give.', 'That’s the part I’ll remember: how much attention you paid.'],
    tone: 'tender',
    significance: 'major',
    treatment: 'video',
    mood: 'tender',
    media: [
      media('video', '/assets/gifts/my-reaction.mp4', 'Winston’s gift-opening reaction', 'Winston opening Gia’s gifts', 'have', 'portrait', { poster: '/assets/gifts/my-reaction-poster.jpg' }),
    ],
    drafted: true,
  },

  /* ───────────── SEPTEMBER 27 — placed just before the reset, not as its cause ───────────── */
  {
    id: 'september-27',
    chapter: 'sept27',
    date: '2026-09-27',
    dateCertainty: 'exact',
    title: 'September 27',
    shortText: 'You went to the ER in severe pain. Scans, medication, care, and then home.',
    longText: [
      'That day brought pain and uncertainty. Across the distance, we prayed for your healing, your peace, and the future we hope to build with God.',
      // our spiritual interpretation, not a medical claim
      'We wondered if it was spiritual opposition to our hope of raising a godly generation. Whatever it was, we placed your health and our future in God’s hands.',
    ],
    tone: 'tender',
    significance: 'medium',
    treatment: 'floating',
    mood: 'quiet',
    transitionIn: 'dark',
    media: [media('screenshot', '/assets/september-27/messages.jpg', 'Messages from that day (optional)', 'Messages from September 27', 'find')],
    drafted: true,
  },

  /* ───────────── IX · RETURNING TO OUR FIRST LOVE ───────────── */
  {
    id: 'first-love',
    chapter: 'firstlove',
    date: '2026-09-30',
    dateLabel: 'September 30 – October 2, 2026',
    dateCertainty: 'exact',
    title: 'Returning to our first love',
    shortText: 'We had both grown dry with God.',
    longText: [
      'So we fasted on Wednesday and Thursday, and talked on Friday.',
      'Not because everything was fixed. To come back to God first, and walk forward together.',
    ],
    tone: 'quiet',
    significance: 'medium',
    treatment: 'quiet',
    mood: 'candle',
    transitionIn: 'dark',
    drafted: true,
  },

  /* ───────────── CHAPTER 20 — today ───────────── */
  {
    id: 'birthday-package',
    chapter: 'today',
    date: '2026-10-06',
    dateCertainty: 'exact',
    title: 'Your birthday package',
    shortText: 'Opened.',
    tone: 'joyful',
    significance: 'small',
    treatment: 'floating',
    mood: 'dawn',
    media: [media('image', '/assets/today/package-reaction.jpg', 'Birthday photo / package reaction', 'Gia with her birthday package', 'find', 'portrait')],
  },
];
